### ISSUE TITLE
Discussion: Use cases for `useAuthenticator` Hook

### ISSUE THREAD

**Issue by vymao** [aws-amplify/amplify-ui#1497]
The original issue has since been resolved, however, leaving this open due to good discussion around use cases for the `useAuthenticator` hook

Original ticket below:

--------------------------

### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create React App

### Please describe your bug.

I am trying to use the `useAuthenticator` hook to set a global authentication state. 

However, several problems have arisen: 
1. When I use `const { user, signOut } = useAuthenticator((context) => [context.user]);`, as is mentioned [here](https://ui.docs.amplify.aws/components/authenticator#access-authenticated-user), there is no app-level re-rendering. So several other components that are also using the hook and are dependent on authentication state don't change. 
2. If I refresh the page, React renders everything as signed out. When I go to sign in, it then signs me in automatically without me having to manually sign in. It should ideally render everything as signed in from the start, since I am already signed in. 

### What's the expected behaviour?

When I sign in or out, React should trigger an app-level re-render with the new authentication state. Furthermore, if I refresh the page, the authentication state should not change. 

### Help us reproduce the bug!

Following the instructions, I added `Authenticator.Provider` at the app level: 
```
ReactDOM.render(
  <Authenticator.Provider>
    <HelmetProvider>
      <BrowserRouter>
        <App />
      </BrowserRouter>
    </HelmetProvider>
  </Authenticator.Provider>,
  document.getElementById('root')
);
```
I use `useAuthenticator` to Login: 
```
const { route } = useAuthenticator(context => [context.route]);
    return (
        route === 'authenticated' ? <Navigate to="/dashboard/app" />: (
            <Authenticator
                // Default to Sign Up screen
                initialState="signUp"
                // Customize `Authenticator.SignUp.FormFields`
                signUpAttributes={['preferred_username', 'birthdate']}
                components={components}
                services={{
                    async validateCustomSignUp(formData) {
                        if (!formData.acknowledgement) {
                            return {
                                acknowledgement: 'You must agree to the Terms & Conditions',
                            };
                        }
                    },
                }}
            />
        )
            );
```
I define `const { user, signOut } = useAuthenticator((context) => [context.user]);` in components, not at the app level, where I want to obtain the authentication state. Following the guide, I use the conditional `typeof user === 'undefined'` to see if the user is authenticated.

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by ErikCH** [comment]
Hi @vymao !

Yes, we have seen the issue with the `useAuthenticator` hook not updating on refresh. We are tracking that issue [here](https://github.com/aws-amplify/amplify-ui/pull/1492) as well.

I believe the issue you are having with it not tracking on signIn/signOut are related. We'll be looking at this problem soon.

**Comment by vymao** [comment]
Is there a recommended workaround?

**Comment by wlee221** [comment]
Yep, this is a bug -- I believe the root cause is the same as #1332. as of now <Authenticator /> needs to be in the component tree for it to properly transition to the route 'authenticated' . 

Meaning whenever you're on `/dashboard/app`, there's no `Authenticator` on that DOM tree, and `useAuthenticator` fails to load the current auth state. 

As per workaround, can you try putting an "invisible" authenticator inside your `/dashboard/app` and let us know if that works? We'll prioritize a fix meanwhile.

**Comment by vymao** [comment]
I'm not sure I understand. Is adding `Authenticator.Provider` not enough? From my understand of context in React, using a proper hook should only look for a provider up the DOM tree, and since I place the provider at the App level, it in theory should re-render everything, no? 

Also I'm not sure what you mean by "invisible" authenticator. I have the actual `Authenticator` as a separate component because I want to still enable users to use part of the app while not signed in.

**Comment by wlee221** [comment]
Yep your comment on `Context` is right. And this is only a workaround, we're fixing it holistically soon. 

The root cause is that `Authenticator`, when rendered, is sending some data to `Authenticator.Provider` to initialize the auth state management. So whenever there's an `<Authenticator.Provider>` but not an `<Authenticator />`, `<Authenticator.Provider />` does not have the auth information ready and will not provide the up-to-date context. So the flow is like this:

1. `<Authenticator.Provider />` renders, but have not started auth state management yet
2. `<Authenticator />` renders, and `Authenticator` starts the  auth flow inside `Authenticator.Provider`

which is an anti-pattern in React and what we'll prioritize fixing.

That's why I mentioned an invisible `Authenticator`: Assume you have signed in and refresh in `dashboard/app` page. In `dashboard/app`, (I assume) that signed in pages does not have an `Authenticator` in the tree, and so it'll think that the user is not authenticated. So this should address your problem (2).

In terms of (1), that is app-level re-rendering, do you have the same problem if you have `useAuthenticator(context => [context.route])`? It should cause a re-render whenever there's a valid user in the tree. Without that, you won't be even able to automatically traverse to `dashboard/app`, right? The authenticator state should change when you sign in with the Authenticator.

**Comment by vymao** [comment]
I guess I mean to say: how does one incorporate an invisible `Authenticator`? I'm probably misunderstanding, but wouldn't adding `Authenticator` to the `dashboard/app` component render a new sign in page instead? That isn't my intent.

**Comment by ErikCH** [comment]
@vymao Could you try adding an `<Authenticator>` to the route and add css to hide it.

```
[data-amplify-authenticator] {
display:none;
}
```

**Comment by vymao** [comment]
Seems to work that way, thanks. But I think this still isn't ideal; my app has a separate login page that actually uses `Authenticator`; placing this hidden `Authenticator` above that also hides the actual `Authenticator`. So it seems one can only use this in the DOM tree which doesn't have another `Authenticator` in use below it, which can be a hassle to manage.

**Comment by wlee221** [comment]
Yep, +1 on it not being ideal at all, and It's an anti-pattern. We'll have a holistic fix soon.

**Comment by vymao** [comment]
Wanted to come back to this and mention that @wlee221 and @ErikCH the solution involving hiding Authenticator seems to only work if the user is signed in. If the user is signed out, the Authenticator still appears. 

To provide more context for how I used this: 
In my routes, I use layouts for different pages: 
```

export default function Router() {
  return useRoutes([
    {
      path: '/dashboard',
      element: <DashboardLayout />,
      children: [
        { path: '', element: <Navigate to="/dashboard/app" /> },
        { path: 'app', element: <DashboardApp /> },
        { path: 'user', element: <User /> },
        { path: 'products', element: <Products /> },
        { path: 'blog', element: <Blog /> },
      ]
    },
    { path: '*', element: <Navigate to="/404" replace /> }
  ]);
}

```
Such a layout is like: 
```
export default function DashboardLayout() {
  const [open, setOpen] = useState(false);

  return (
    <RootStyle>
      <Authenticator />
      <DashboardNavbar onOpenSidebar={() => setOpen(true)} />
      <DashboardSidebar isOpenSidebar={open} onCloseSidebar={() => setOpen(false)} />
      <MainStyle>
        <Outlet />
      </MainStyle>
    </RootStyle>
  );
}

```
which imports the CSS file containing: 
```
[data-amplify-authenticator] {
    display: none;
}
```

**Comment by ErikCH** [comment]
Hi @vymao !

Does this problem still occur?

**Comment by vymao** [comment]
Yes. Was there an update that fixed this?

**Comment by ErikCH** [comment]
Hi @vymao !

Yes, so we made a change with #1580 that improves the experiences for users that are on multiple routes. So now as long as you have your application surrounded by `Authenticator.Provider` the `useAuthenticator` will work on any route you're on. Before, if you didn't have an `Authenticator` on your page it wouldn't work.

There is still one more outstanding issue with this solution. On refresh the `route` will temporarily be in a `setup` or `idle` state before it transitions to an `authenticated` state. If you check route as soon as the page loads, and redirect somewhere while it's in the `idle` or `setup` state, that could be an issue.

I created a guide on authenticated routes [here](https://ui.docs.amplify.aws/guides/auth-protected#adding-in-a-requireauth-component). In it I describe this scenario, and work around for it. 

In this scenario if someone goes to an authenticated route, and it's an `idle` or `setup` state then we redirect back to `/login`. Which will then by that time see the user is `authenticated` and will re-route back to the `authenticated` page. 

Let me know if that's what you're experiencing and if this work around helps in the mean time.

**Comment by vymao** [comment]
It seems to work for now, will report back if any issues. Thanks!

**Comment by silberistgold** [comment]
Not entirely sure but I think this is related: I have a route where I sign in the user via input from a custom form and not `Authenticator` is in the tree. I used to do this via `Auth.signIn` but this does not propagate AuthState into `Authenticator` or `useAuthenticator` although everything is wrapped in `Authenticator.Provider`.
My current workaround is to use `submitForm` from `useAuthenticator` hook and dispatch an event like this:

```
submitForm({
      type: "SIGN_IN",
      username: "foo@bar.com",
      password: "12345678",
});
```

This works but as far as I can tell it is undocumented and relies on the internal event name and structure. Can you elaborate on the use case for `submitForm` and the validity of this workaround. Also am I missing some way to signIn the user with pre-obtained credentials via the `useAuthenticator` hook without displaying an `Authenticator`?

**Comment by ErikCH** [comment]
Hi @silberistgold !

If you're using `Auth.signIn`, that will not propagate to `useAuthenticator` or the auth state. You are correct. 

The only thing we listen for is `Auth.signOut`. That will propagate. We are looking at adding more `hub events` to listen to, so you can interact directly with the JS library, outside of the `Authenticator`.

The `submitForm` is an internal event name, and it's not mentioned in our documentation. It's used for both sending the `signUp` and `signIn` information. Just beware, you need to be on the correct route, for it to work. You can use the `toSignUp` or `toSignIn` to get to that.

With all that said, I wouldn't recommend using it in the long term, since it could change. However, we are looking into adding better documentation and more utilities to make creating your own headless `Authenticator` a better experience for advanced used cases like yours.

**Comment by wlee221** [comment]
Hi all, we'll close this issue because @vymao's original issue is resolved.

For @silberistgold's comment: 

> I guess some of the initialisation logic has to be moved into Authenticator.Provider for this to be working. Are there any plans for doing this?

Yep, precisely. We are looking to move some props from `Authenticator` to `Authenticator.Provider` so that underlying auth service can start independently of `Authenticator`. This will have to be in next major release because it'll be a breaking change. cc @calebpollman

> Without Authenticator the route is stuck at setup and using toSignIn or submitForm has no effect (as it is expected for invalid transitions). I am using version 2.16.0.

This is likely an edge case we missed. Does this happen after you authenticate, or before? If it's after, this is a bug; #1580 was intended to resolve this by automatically switching route to `authenticated` if there's a current user whether or not there's an `Authenticator` in the DOM tree. If it's before, it's very likely a use case we missed. Can you open a new issue if so?

**Comment by reesscot** [comment]
Reopened since we need to address the overall use cases mentioned by @kyokosdream

**Comment by reesscot** [comment]
@kyokosdream It is now possible to Automatically sign in using the JS Auth API's. See
https://docs.amplify.aws/lib/auth/emailpassword/q/platform/js/#auto-sign-in-after-sign-up

We are working on supporting your use cases above, and will update this ticket when we have more detailed plan.

**Comment by snirlugassy** [comment]
In the meanwhile, I've used **"window.location.reload(true)"** right after I sign in in order to force the authenticator provider to update. It's not a good practice but it worked for now..

**Comment by siulca** [comment]
It's quite unbelievable that this has not yet been fixed after 1 year! Come on guys, lots of devs rely on this stuff.

**Comment by kallsbo** [comment]
I ran into this as well, especially if I refreshed the application. I ended up putting together a quick user provider of my own:

````
import { createContext, useState, useEffect } from 'react';
import { Hub, Auth } from 'aws-amplify';

export const UserContext = createContext();

export const UserProvider = ({ children }) => {
    const [user, setUser] = useState(null);
    const signOut = () => Auth.signOut();

    useEffect(() => {
        // Check the current user when the app loads
        Auth.currentAuthenticatedUser().then(user => setUser(user)).catch(() => console.log('Not signed in'));

        // Listen for changes to the Auth state and set the local state
        const hubListenerCancelToken = Hub.listen('auth', (data) => {
            const { payload } = data;
            console.log('A new auth event has happened: ', data.payload.event);
            onAuthEvent(payload);
        });

        return () => {
            hubListenerCancelToken();
        }
    }, []);

    const onAuthEvent = (payload) => {
        switch (payload.event) {
            case 'signIn':
                return setUser(payload.data);
            case 'signOut':
                return setUser(null);
            default:
                return;
        }
    }

    return (
        <UserContext.Provider value={{ user, signOut }}>
            {children}
        </UserContext.Provider>
    );
}
````

Then I use it where ever I need user info like a top menu or anything else:

````
import { useContext } from 'react';
import { UserContext } from '../components/UserContext';

function TopMenuBar() {
    const { user, signOut } = useContext(UserContext);
    ....
````

That works for both reloading and auth changes. I have a separate Login page where I just use the Authenticator and my own context to check if I should redirect back:

````
import { useEffect, useContext } from "react";

import { UserContext } from "../components/UserContext";

import { Authenticator, View } from "@aws-amplify/ui-react";
import '@aws-amplify/ui-react/styles.css';

import { useNavigate, useLocation } from "react-router-dom";

export default function Login() {
    const { user } = useContext(UserContext);
    const location = useLocation();
    const navigate = useNavigate();
    const from = location.state?.from || "/";

    useEffect(() => {
        if(user) {
            navigate(from, { replace: true });
        }
    }, [user, navigate, from]);

    return (
        <View className="auth-wrapper">
            <Authenticator />
        </View>
    );
}
````

Hope this helps someone in the meantime!

**Comment by ioanabrooks** [comment]
@kallsbo Using the latest version of 
```
const { route, user, signOut } = useAuthenticator((context) => [context.route, context.user]);
 ```
without the need to implement a custom provider.  Please let us know what issues you are running into.

**Comment by kallsbo** [comment]
> @kallsbo Using the latest version of `@aws-amplify/ui-react` you should be able to use:
> 
> ```
> const { route, user, signOut } = useAuthenticator((context) => [context.route, context.user]);
> ```
> 
> without the need to implement a custom provider. Please let us know what issues you are running into.

When I have a page refresh I lose the updates when the user changes status like logout etc.

**Comment by reesscot** [comment]
@kallsbo Can you explain more what type of state you are losing when you refresh the page? Are you navigating between routes in your application, or is this a full browser page refresh? Are you not seeing the user object updated when you refresh the page? Would love to learn more about why the default `useAuthenticator` is not working for you

**Comment by yannickrocks** [comment]
Hi there

Is there any update on this?

**Comment by yannickrocks** [comment]
Hi there

Am i right in understanding that building your own custom component and trying to invoke the `submitForm` method for signing in does nothing? 

I am using it as follows on the route `signIn` and it seems to do nothing

```
    submitForm({
      type: 'SIGN_IN',
      username: email,
      password,
    });
```

Would you also be able to use the `submitForm` method for RESET_PASSWORD as it is one of the `AuthEventTypes`?

**Comment by farleyta** [comment]
> Would love to learn more about why the default `useAuthenticator` is not working for you

@reesscot I'll add to this – one of the ways in which `useAuthenticator` seems to be not working as I would expect is in regards to "headless" usage of `Authenticator.Provider`, with a custom UI (in my case, via `Auth.signUp`).

[This earlier answer](https://github.com/aws-amplify/amplify-ui/issues/1497#issuecomment-1115188487) from @ErikCH was really helpful – this seems to be the exact issue I'm running into.

> If you're using Auth.signIn, that will not propagate to useAuthenticator or the auth state. You are correct.

> The only thing we listen for is Auth.signOut. That will propagate. We are looking at adding more hub events to listen to, so you can interact directly with the JS library, outside of the Authenticator.

Can you please confirm that this is indeed still an issue?  If so, it seems the "roll your own provider" approach is the best way forward for now?  Is there any plan to continue to add support for the additional hub events propagating to `useAuthenticator`?

**Comment by reesscot** [comment]
@farleyta This should be fixed in https://github.com/aws-amplify/amplify-ui/pull/3806, and you should now be able to try it by installing the `next` tagged version. Can you please test it out, and let us know if this fixes your issue?
```
npm install @aws-amplify/ui-react@next
```

**Comment by farleyta** [comment]
It does seem to be working for me now @reesscot!  Still having some issues, but I think they may be on my end, elsewhere in the code.  In console logs, I'm seeing updated values for `user` and `authState` as expected from `useAuthenticator` after signIn.  Previously, I wasn't seeing updated values. Thanks!

One thing I didn't explicitly check is `autoSignIn`, which I think utilizes a different `Hub` event.  We don't need it for our current use case, but would be good to ensure that it supported as well.

Either way, thanks for digging in.  Much appreciated!

**Comment by zchenwei** [comment]
> It does seem to be working for me now @reesscot! Still having some issues, but I think they may be on my end, elsewhere in the code. In console logs, I'm seeing updated values for `user` and `authState` as expected from `useAuthenticator` after signIn. Previously, I wasn't seeing updated values. Thanks!
> 
> One thing I didn't explicitly check is `autoSignIn`, which I think utilizes a different `Hub` event. We don't need it for our current use case, but would be good to ensure that it supported as well.
> 
> Either way, thanks for digging in. Much appreciated!

@farleyta You are welcome! Glad to see that help!

**Comment by movingelectrons** [comment]
this is still a problem?  is for me anyways, this is a temporary workaround change RequireAuth.js to

`export function RequireAuth({ children }) {
  const location = useLocation();
  //const { route } = useAuthenticator((context) => [context.route]);
  try {
    Auth.currentAuthenticatedUser()
  } catch (error) {
    return (
      <Navigate to="/signin" state={{ from: location }} replace />
    );
  }
  return children;
}`

but it never gets to the catch, but it does prevent non loged in users from accessing pages like it should.

**Comment by adriaanbalt** [comment]
This is a pretty long thread and it seems to have gone in a few directions, so hopefully this is still related.

### Backstory:
I'm using AWS Amplify with React Native.  https://www.npmjs.com/package/@aws-amplify/ui-react-native
I want to customize the UI for my sign in and signup experiences.  

### What worked but without a custom UI
I discovered that using the "out of the box" UI like this:
```
 <Authenticator>
  {children}
</Authenticator>
```
Allowed me to create a user, login with that user and upon login in the view would re-render to reveal the `{children}`.  

### Custom Sign In UI doesn't re-render...
Great the previous approach allowed me to login, but it used AWS Amplify's UI, and desire more control.  So I started writing this:
```
 <Authenticator
components={{
      SignIn: props => {
        return <MySignIn {...props} />;
      },
      SignUp: props => {
        return <MySignUp {...props} />;
      },
    }}
    Header={MyHeader}
    Footer={Footer}
>
  {children}
</Authenticator>
```
Although my UI looked pretty, whenever I invoked `const res = await signIn({ username, password });` within MySignIn component on press of the "Sign In" button, the UI would not re-render.  It would not reveal my `{children}`, like it did before with the out of the box UI.

### Solution

It appears that after authenticating, the user is not picked up and stored within the Authenticator, and thus not passed into the children.  Even though the `authStatus` does change to "Authenticated" it doesn't appear to also store the user.  And my {children} components rely on that user data.

The only way I was able to get around this is by doing the following.

First I needed to update my Authentication file:
```
<Authenticator.Provider>
    <>
      {authStatus === 'unauthenticated' && (
        <Authenticator
          components={{
            SignIn: props => {
              return <MySignIn {...props} />;
            },
            SignUp: props => {
              return <MySignUp {...props} />;
            },
          }}
          Header={MyHeader}
          Footer={Footer}
        >
          {children}
        </Authenticator>
      )}
      {authStatus === 'authenticated' && children}
  </>
</Authenticator.Provider>
```

Then inside the component that is in the `{children}`, in my case `<Wrapper>` I had to add this:

```
import { fetchAuthSession } from 'aws-amplify/auth';
const { authStatus } = useAuthenticator();
const [user, setUser] = React.useState<AuthUser | undefined>(undefined);
useEffect(() => {
  const fetchSession = async () => {
    const res = await fetchAuthSession();
    setUser(res.tokens);
  };
  fetchSession();
}, [authStatus]);
```

This properly retrieved the user after login and set it into the user state.  

I had hoped instead to not have to do this.  Instead I assumed that in Wrapper I could get the user like this `const { user, authStatus } = useAuthenticator();` and not have to run the `fetchAuthSession()` method.

If there is an alternative approach I'm very open to using it.  This feels like a work around because using the AWS Amplify "out of the box" UI does in fact trigger the re-render and reveal the children.  Not sure why my custom UI approach with `signIn()` doesnt work..

### Other findings

If you look at the compiled code within node_module OR here https://www.npmjs.com/package/@aws-amplify/ui-react-native?activeTab=code you will find `/@aws-amplify/ui-react-native/dist/Authenticator/Authenticator.js` and within this file you can see these lines of code:
```
....
const { Component, props } = useAuthenticatorRoute({ components });
const typedFields = getRouteTypedFields({ fields, route });
const isAuthenticatedRoute = route === 'authenticated' || route === 'signOut';
if (isAuthenticatedRoute) {
    return children ? <>{children}</> : null;
}
return (<SafeAreaProvider>
  <Container>
    {Header ? <Header /> : null}
    <InnerContainer>
      <Component {...props} fields={typedFields}/>
    </InnerContainer>
    {Footer ? <Footer /> : null}
  </Container>
</SafeAreaProvider>);
...
```

As you can see, the children should be rendered when the route `isAuthenticatedRoute = route === 'authenticated' || route === 'signOut'` but this doesn't seem to happen (not sure why).

**Comment by calebpollman** [comment]
Hey @adriaanbalt. Are you calling `signIn` directly from inside `MySignIn`?

**Comment by adriaanbalt** [comment]
@calebpollman yes

**Comment by calebpollman** [comment]
@adriaanbalt  Can you try replacing the call to `signIn` with `handleSubmit` from `useAuthenticator`? The internal state informing the UI of the  `Authenticator` doesn't have awareness of calls made directly to `signIn` (same issue with calling `signUp` directly in the `SignUp` component)

**Comment by adriaanbalt** [comment]
@calebpollman 
`handleSubmit` does not appear to be available on `useAuthenticator` hook.
See screenshot:
![Screenshot 2024-01-12 at 8 32 27 PM](https://github.com/aws-amplify/amplify-ui/assets/146778/5ab91ebb-5344-423d-802a-49e648e61c5f)

**Comment by calebpollman** [comment]
@adriaanbalt That was a mistake on my end. It's available as a prop passed in to the `SignIn` component:
```
components={ SignIn: ({ handleSubmit, ...props }) => {
  // ...do custom UI stuff
  }
}
```

**Comment by adriaanbalt** [comment]
@calebpollman 
this works.  I have removed my previous `fetchAuthSession` code.

![Screenshot 2024-01-12 at 8 53 08 PM](https://github.com/aws-amplify/amplify-ui/assets/146778/6f03eb36-dea9-4b32-9ae8-3d2573c43346)


Question: Why is this information so difficult to find and not an obvious alternative?

**Comment by calebpollman** [comment]
@adriaanbalt Glad that you got things working!

> Question: Why is this information so difficult to find and not an obvious alternative?

The documentation could be improved here, think the addition of a concrete example for this use case would be a good starting point but curious if there is anything else that you would have found helpful?

**Comment by adriaanbalt** [comment]
@calebpollman 

Generally, the documentation is good, but since time has changed the capabilities it seems like it is a bit dated.

Firstly, the documentation relies on examples.  There isn't the classic documentation style that outlines each property, class or method that is available on each hook or module.  This would already be helpful and probably easier to maintain.  When something is deprecated the page that the information is displayed can also say it has been deprecated.  This is relatively common when reviewing documentation for other APIs.

Secondly, currently the AWS Amplify customization docs suggest [this approach](https://ui.docs.amplify.aws/react/connected-components/authenticator/advanced#authentication-check) but this is not quite right because the NBM "module itself seems to handle the revealing of the children (see my [earlier post's](https://github.com/aws-amplify/amplify-ui/issues/1497#issuecomment-1889811846) "Other finds" section).

Lastly, if you search for "handlesubmit" on the authenticator documentation page the word doesn't exist
<img width="1010" alt="Screenshot 2024-01-13 at 2 54 27 PM" src="https://github.com/aws-amplify/amplify-ui/assets/146778/a3f0ee1f-a527-4bb9-8e22-503b562cdec9">
It would at the bare minimum be helpful to know that this exists as a prop when instantiating a custom "Sign In" view.

For an example, you can go with the a basic approach, which satisfies almost all use-cases.

Use case: I want to add custom authentication to my app.
Result:

#### Provider
```
<Authenticator.Provider>
  <Authenticator
    components={{
      SignIn: props => {
        return <MySignIn {...props} />;
      },
      SignUp: props => {
        return <MySignUp {...props} />;
      },
    }}
    Header={MyHeader}
    Footer={Footer}
  >
    {children}
  </Authenticator>
</Authenticator.Provider>
```

#### MySignIn component
```
const MySignIn: React.FC<any> = ({ toSignUp, handleSubmit }) => {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');

  const handleSignIn = async () => {
    try {
      await handleSubmit({ username, password });
    } catch (error) {
      console.error('Error signing in:', error);
    }
  };
  return (
    <View
      style={{
        marginTop: 24,
        padding: 24,
      }}
    >
      <TextInterBold style={[Styles.h2, { marginBottom: 30 }]}>
        Sign in
      </TextInterBold>
      <View
        style={{
          marginBottom: 30,
        }}
      >
        <Input
          style={Styles.input}
          placeholder="Username"
          onChangeText={text => setUsername(text)}
          value={username}
          autoComplete="email"
        />
        <Input
          style={Styles.input}
          placeholder="Password"
          secureTextEntry={true}
          onChangeText={text => setPassword(text)}
          value={password}
          autoComplete="password"
        />
      </View>
      <View
        style={{
          flexDirection: 'row',
          justifyContent: 'space-between',
          marginTop: 10,
          marginBottom: 30,
        }}
      >
        <Button
          style={[Styles.button, { width: '25%' }]}
          onPress={handleSignIn}
        >
          Sign In
        </Button>
        <Button style={[Styles.button, { width: '25%' }]} onPress={toSignUp}>
          Create an account
        </Button>
      </View>
    </View>
  );
};

export default MySignIn;
```

Note the use of `handleSubmit` versus what the documentation suggests with is `signIn()`

[You can see the documentation suggests using `signIn()` here.](https://docs.amplify.aws/react-native/build-a-backend/auth/enable-sign-up/#sign-in) and in several other places for [JavaScript](https://docs.amplify.aws/javascript/build-a-backend/auth/enable-sign-up/#sign-in) or [React](https://docs.amplify.aws/react/build-a-backend/auth/enable-sign-up/#sign-in).  This is misleading as we both know that this doesn't work as expected.

I would suggest including information at this point in the documentation that explains the use of `handleSubmit`, even if this is a temporary alternative and a fix is coming in the future.  Because for people like myself I almost had to forego using AWS Amplify due to the lack of ability to log a user in with a custom form.  That is probably not ideal for AWS Amplify.

I hope this helps and wish you luck improving the docs.  Thanks!

**Comment by annjawn** [comment]
I am a little confused by this thread. I tried to implement this with Javascript and `"@aws-amplify/ui-react": "^6.1.3"` but this doesn't seem to work. `<MyAuthentication/>` is my custom Auth page. What am I missing here? 

```javascript
<Authenticator components={{
        SignIn: props => {
          return <MyAuthentication {...props}/>
        },
        SignUp: props => {
          return <MyAuthentication {...props}/>
        }
      }}>
  <BrowserRouter>
   <App />
  </BrowserRouter>
</Authenticator>
```

**Comment by reesscot** [comment]
Hi @annjawn,
I think you may be getting confused because completely overriding the `SignIn` screen is only available in the React Native version of the Authenticator. There is ongoing work to bring this capability to the React Web Authenticator.

**Comment by annjawn** [comment]
Ah ok, I read the previous comment which indicated that it may work. Thanks. so the only option for a fully custom Auth screen experience is to fall back to `aws-amplify`, not sure if I can still use `<Authenticator.Provider>`. I've previously posted in this repo how difficult it is to build a fully custom login experience. There also used to be an example in the docs but that page is now gone.

**Comment by annjawn** [comment]
Well no, i take that back. I don't think that's even possible now that `Auth` doesn't exist in `aws-amplify`. @reesscot what are the options for a fully custom auth experience here?

**Comment by reesscot** [comment]
There is a new version of the Authenticator in the works which will allow full UI customization without having to recreate all the auth flow logic, but it's not available yet.

Yes, you can definitely create your own auth experience using the Amplify Auth JS apis here:
https://docs.amplify.aws/react/build-a-backend/auth/enable-sign-up/

**Comment by timheilman** [comment]
I had much better luck with the Authenticator component and provider when I was using `amplify-js` version 5.  On version 6, not as much luck. I found a workaround that may help others.

I only use `authStatus` from `useAuthenticator`.  This seems to update to "authenticated" upon login using the Authenticator component, but I could not get it to update to "unauthenticated" upon logout. 

I found a workaround for that issue.

I'm also using redux, and at signOut, I do not use the `signOut` method from `useAuthenticator`.  Instead, I use:

`import { signOut } from "aws-amplify/auth";`

And my sign-out button handler then does this: 

```
    void signOut();
    dispatch(setLogoutInt(randomLargeInt()));
```

`setLogoutInt` is a redux action, and `dispatch` is the redux Dispatch.

Then, this was the trick that got things working for me: forcing a rerender of the Provider upon logout via redux:

```
  const logoutInt = useAppSelector(selectLogoutInt);
  return (
    <Authenticator.Provider key={logoutInt}>
      <AppBeneathAuthenticatorProvider />
    </Authenticator.Provider>
  );
```

With this workaround, I am able to use amplify v6 with the Authenticator component and logout successfully. Hope it helps!  Good luck.

**Comment by adriaanbalt** [comment]
@annjawn  implementation is using React Native in a web build configuration as I'm building a project that must work across all platforms. The other comments should also help you though :)

**Comment by annjawn** [comment]
Hi @adriaanbalt, so fully overriding the components in `<Authenticator>` in web/React isn't possible right now, as confirmed by @reesscot yesterday. It's a work in progress. As a workaround, I am working with `aws-amplify/auth` to build the custom Authentication experience, but its yet to be seen if it plays well with `<Authenticator.Provider>`. I will probably find out either today/tomorrow.

**Comment by annjawn** [comment]
Ok, I can confirm that using only `<Authenticator.Provider>` with `aws-amplify/auth` methods works pretty well with `useAuthenticator` for a fully custom UI experience. Here's the simple implementation that works with no force window reload to re-render etc. for login or logout needed and  `useAuthenticator` hook works beautifully

React+Vite

App.jsx
```javascript

function App() {
  const { authStatus } = useAuthenticator((context) => [context.user]);
  
  return (
    <>
    {
      (authStatus === "authenticated")?
      <Routes>
        <Route path="/" element={<AppLayout />}>
          .....//all the app authenticated routes
        </Route>
      </Routes>
      :<Routes>       
          <Route path="/" element={<Authenticate />}>
              <Route index element={<React.Suspense fallback={<Spin/>}>
                                      <Login/> //--> fully custom UI using aws-amplify/auth
                                    </React.Suspense>} />
              <Route path="signup" element={<React.Suspense fallback={<Spin/>}>
                                    <SignUp/>  //--> fully custom UI using aws-amplify/auth
                                  </React.Suspense>} />   
              <Route path="reset" element={<React.Suspense fallback={<Spin/>}>
                                    <Reset/>  //--> fully custom UI using aws-amplify/auth
                                  </React.Suspense>} /> 
          </Route>   
      </Routes>
    }
    </>
  )
}
```

main.jsx
```javascript
ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <Authenticator.Provider>
        <BrowserRouter>
          <App />
        </BrowserRouter>
    </Authenticator.Provider>
  </React.StrictMode>,
)
```

AppLayout.jsx (has SignOut button)

```javascript
const { signOut } = useAuthenticator((context) => [context.user]);

const onSignOut = () => {
        signOut()      
}

return (<button onClick={onSignOut}>Log out</button>)
```

Actually quite shocked to see how well this works.

**Comment by williamtorc** [comment]
My `user` [from `useAuthenticator`] is undefined even tough I'm only rendering when authenticated

```
return authStatus === "authenticated" ? (
    <AuthenticatedRoutes />
  ) : (
    <PublicRoutes />
  );
```

on  `<AuthenticatedRoutes />`

```
const { user } = useAuthenticator((context) => [context.user]);
````

I get undefined and then the user is populated

**Comment by thaddmt** [comment]
@williamtorc are you using the Authenticator component with the user of useAuthenticator? Similar to this comment here `useAuthenticator` is only meant to be used inside of a rendered `Authenticator` and things like `user` and `route `will not work without it - https://github.com/aws-amplify/amplify-ui/issues/5861#issuecomment-2389235304

**Comment by thaddmt** [comment]
Closing this issue as the original bug has been resolved. If you have any new issues please open a new ticket.
