### ISSUE TITLE
Reset password submit button has incorrect label 

### ISSUE THREAD

**Issue by mikejpeters** [aws-amplify/amplify-ui#1784]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Angular

### Which UI component?

Authenticator

### How is your app built?

Webpack

### Please describe your bug.

When using the `<amplify-authenticator>` Angular component, with no customizations, the reset password button says "Send Code" even though the code was sent in the  previous step. 

![image](https://user-images.githubusercontent.com/3334654/165633586-a3a4d249-d495-4e8b-bdd9-318b81c072fc.png)

### What's the expected behaviour?

The button should be labelled something more clear like "Submit" or "Change Password"

### Help us reproduce the bug!

I think this happens in any situation the Angular authenticator is used, during the reset password flow.

Looking at the Angular component, it seems like the wrong label is being set here:

https://github.com/aws-amplify/amplify-ui/blob/8b72277ab8bd7ad64fa298a9d509572318ac8db2/packages/angular/projects/ui-angular/src/lib/components/authenticator/components/confirm-reset-password/amplify-confirm-reset-password.component.ts#L18

https://github.com/aws-amplify/amplify-ui/blob/8b72277ab8bd7ad64fa298a9d509572318ac8db2/packages/angular/projects/ui-angular/src/lib/components/authenticator/components/confirm-reset-password/amplify-confirm-reset-password.component.html#L16-L18

Compared to the Vue component, which seems more correct:

https://github.com/aws-amplify/amplify-ui/blob/8b72277ab8bd7ad64fa298a9d509572318ac8db2/packages/vue/src/components/confirm-reset-password.vue#L38

https://github.com/aws-amplify/amplify-ui/blob/8b72277ab8bd7ad64fa298a9d509572318ac8db2/packages/vue/src/components/confirm-reset-password.vue#L100-L108

### Code Snippet

```html
<div class="ion-padding">
  <amplify-authenticator>
    <ng-template amplifySlot="authenticated">
      <ion-app>
        <ion-router-outlet></ion-router-outlet>
      </ion-app>
    </ng-template>
  </amplify-authenticator>
</div>
```

**Comment by ErikCH** [comment]
Hi @mikejpeters !

I was able to reproduce this! We'll get this fixed!

**Comment by slaymance** [comment]
I've verified this is only occurring in the Angular implementation. As pointed out, it seems a simple case of updating the button text to "Submit".

**Comment by slaymance** [comment]
Fixed in [@aws-amplify/ui-angular@2.3.15](https://github.com/aws-amplify/amplify-ui/releases/tag/%40aws-amplify%2Fui-angular%402.3.15).

**Comment by mikejpeters** [comment]
Thank you for the quick turnaround, unfortunately it's still broken for me with 2.3.15.

I tracked down the issue:

https://github.com/aws-amplify/amplify-ui/blob/04132afc16167b3fd2015d097a840c555a0cb3da/packages/angular/projects/ui-angular/src/lib/components/authenticator/components/confirm-reset-password/amplify-confirm-reset-password.component.ts#L27-L29

The `hasTransation` function returns `false` if the translated phrase is equal to the original phrase:

https://github.com/aws-amplify/amplify-ui/blob/4a091bb01666ef99e6d5dc977460cf73132738e4/packages/ui/src/i18n/translations.ts#L73-L75

So in this case because "Submit" is translated to "Submit" in english, `hasTransaltion` returns `false`, and the legacy behavior (using "Send Code") is run.

**Comment by mikejpeters** [comment]
Hopefully this issue will get re-opened, but in the meantime I did find a workaround. Basically you just have to define the translation for "Submit" to something besides "Submit" - even just by adding some space around it, which won't be rendered:

```ts
import { translations } from '@aws-amplify/ui-angular';
import { I18n } from 'aws-amplify';

I18n.putVocabularies(translations);
I18n.setLanguage('en');
I18n.putVocabulariesForLanguage('en', {
  Submit: ' Submit ',
});
```

In my project I added this in `main.ts`, just after `Amplify.configure(aws_exports);`

**Comment by ErikCH** [comment]
We'll look at this again!

**Comment by localsecurity-emily** [comment]
> Hopefully this issue will get re-opened, but in the meantime I did find a workaround. Basically you just have to define the translation for "Submit" to something besides "Submit" - even just by adding some space around it, which won't be rendered:
> 
> ```ts
> import { translations } from '@aws-amplify/ui-angular';
> import { I18n } from 'aws-amplify';
> 
> I18n.putVocabularies(translations);
> I18n.setLanguage('en');
> I18n.putVocabulariesForLanguage('en', {
>   Submit: ' Submit ',
> });
> ```
> 
> In my project I added this in `main.ts`, just after `Amplify.configure(aws_exports);`

Thanks @mikejpeters I appreciate the workaround :)

**Comment by ErikCH** [comment]
Hi @localsecurity-emily and @mikejpeters !

We made another fix, it should be in our next release Thursday.
