### ISSUE TITLE
Build error with @floating-ui\core and Create React App

### ISSUE THREAD

**Issue by sam159** [aws-amplify/amplify-ui#3210]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create React App

### Please describe your bug.

Building a new project with this package results in the following error

```
TypeError: C:\Users\Sam\WebstormProjects\untitled\node_modules\@floating-ui\core\dist\floating-ui.core.browser.min.mjs: Cannot read properties of undefined (reading 'constantViolations')
    at transformFile.next (<anonymous>)
    at run.next (<anonymous>)
    at transform.next (<anonymous>)
```

### What's the expected behaviour?

build to succeed

### Help us reproduce the bug!

tested with node 18

1) start new project with `npx create-react-app test-bug --template typescript`
2) install amplify ui `npm i @aws-amplify/ui-react aws-amplify`
3) update `src/App.tsx` to the below content
4) build `npm run build`

### Code Snippet

```typescript
// src/App.tsx
import React from 'react';
import {withAuthenticator, WithAuthenticatorProps} from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';
import './App.css';

function App({ signOut, user } : WithAuthenticatorProps) {
  return (
      <div className="App">
        <p>Hello {user?.username || '?'}</p>
        <button onClick={signOut}>Sign out</button>
      </div>
  );
}

export default withAuthenticator(App);

```

### Additional information and screenshots

```json
{
  "dependencies": {
    "@aws-amplify/ui-react": "^4.3.0",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.5.2",
    "@types/node": "^16.18.10",
    "@types/react": "^18.0.26",
    "@types/react-dom": "^18.0.9",
    "aws-amplify": "^5.0.7",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "typescript": "^4.9.4",
    "web-vitals": "^2.1.4"
  }
}
```

**Comment by sam159** [comment]
until the next version of floating-ui is released the work around is to use the non-minified js from floating-ui. see https://github.com/floating-ui/floating-ui/issues/2062#issuecomment-1362974188

**Comment by seeratawan01** [comment]
![image](https://user-images.githubusercontent.com/26021449/209194474-43303da1-ced0-4fe3-92fb-f8b3b64bcafb.png)
yes same

**Comment by reesscot** [comment]
Opened a bug with babel here: https://github.com/babel/babel/issues/15302

**Comment by nishadthajudeen001** [comment]
any updates? below error with @babel/plugin-transform-block-scoping@7.20.8
./node_modules/@angular/cdk/fesm2015/table.mjs - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
[12:23:32 ](http://build.xpo.pvt/buildConfiguration/Dms20_CiIntScheduled_KubernetesBuilds_BuildApi_HammerLaneWmsPortal_Build1/2378234?buildTab=log&focusLine=230&linesState=230)TypeError: /app/node_modules/@angular/cdk/fesm2015/table.mjs: Cannot set property 'kind' of undefined
[12:23:32 ](http://build.xpo.pvt/buildConfiguration/Dms20_CiIntScheduled_KubernetesBuilds_BuildApi_HammerLaneWmsPortal_Build1/2378234?buildTab=log&focusLine=231&linesState=231)at transformBlockScopedVariable (/app/node_modules/@babel/plugin-transform-block-scoping/lib/index.js:122:41)
[12:23:32 ](http://build.xpo.pvt/buildConfiguration/Dms20_CiIntScheduled_KubernetesBuilds_BuildApi_HammerLaneWmsPortal_Build1/2378234?buildTab=log&focusLine=232&linesState=232)at PluginPass.VariableDeclaration (/app/node_modules/@babel/plugin-transform-block-scoping/lib/index.js:81:9)
[12:23:32 ](http://build.xpo.pvt/buildConfiguration/Dms20_CiIntScheduled_KubernetesBuilds_BuildApi_HammerLaneWmsPortal_Build1/2378234?buildTab=log&focusLine=233&linesState=233)at newFn (/app/node_modules/@babel/traverse/lib/visitors.js:159:21)
[12:23:32 ](http://build.xpo.pvt/buildConfiguration/Dms20_CiIntScheduled_KubernetesBuilds_BuildApi_HammerLaneWmsPortal_Build1/2378234?buildTab=log&focusLine=234&linesState=234)at NodePath._call (/app/node_modules/@babel/traverse/lib/path/context.js:46:20)

**Comment by reesscot** [comment]
If you're using NPM, override the `@babel/plugin-transform-block-scoping` dependency to the known good version:

```
 "overrides": {
    "@babel/plugin-transform-block-scoping": "7.20.5"
  }
 ```

 or Yarn:
 ```
"resolutions": {
     "@babel/plugin-transform-block-scoping": "7.20.5"
  },
 ```

**Comment by sam159** [comment]
@reesscot thanks, that fixes the issue for me

**Comment by hannan-m** [comment]
Facing similar issue with `@fluentui/react` as well.

```
node_modules\@floating-ui\core\dist\floating-ui.core.browser.min.mjs: Cannot set properties of undefined (setting 'kind')
    at transformFile.next (<anonymous>)
    at run.next (<anonymous>)
    at transform.next (<anonymous>)
```

**Comment by reesscot** [comment]
@hannan-m Does the overrides/resolutions fix above work for you?

**Comment by reesscot** [comment]
This [babel bug](https://github.com/babel/babel/issues/15302) has been fixed in `@babel/plugin-transform-block-scoping@7.20.9`. For anyone following this tread, you can remove your overrides and update your package lock files to get the fix without the overrides workaround.

**Comment by hannan-m** [comment]
> @hannan-m Does the overrides/resolutions fix above work for you?

Yes, it does.

**Comment by joywin-dev** [comment]
Hi All - Facing the same issue. Locally the solution of changing the package.json file for flowbite library works. But I am deploying it on aws amplify. And on deploy the build over there fails. Any idea on how I can solve this

**Comment by reesscot** [comment]
@joywin-dev Can you please open an issue over on the hosting repo with the error you're getting? https://github.com/aws-amplify/amplify-hosting/issues

**Comment by joywin-dev** [comment]
> @joywin-dev Can you please open an issue over on the hosting repo with the error you're getting? https://github.com/aws-amplify/amplify-hosting/issues

It is the same issue. Build works well on local after changing the package.json to unminified version. But the code is then pushed to github. But the nodmodules is not pushed. Then the hosting platform picks up the code from github and i get the build error which i had resolved in my local build.

**Comment by reesscot** [comment]
@joywin-dev If it's working locally but not during build, it sounds like it could be a caching issue during the build on amplify hosting. I would recommend opening an issue over there so the hosting team can further assist.

**Comment by joywin-dev** [comment]
@reesscot - Thanks for your help! Also is this issue going to be fixed? Any update from floating-ui team?

**Comment by reesscot** [comment]
@joywin-dev The issue was a babel bug which has been fixed:

> This [babel bug](https://github.com/babel/babel/issues/15302) has been fixed in `@babel/plugin-transform-block-scoping@7.20.9`. For anyone following this tread, you can remove your overrides and update your package lock files to get the fix without the overrides workaround.

**Comment by kaimoeller** [comment]
Hi! I am running into the same issue and have updated the referenced version in package-lock.json file to 7.20.9. But the error persists on amplify publish attempt. What am I missing? Thanks

```
Publish started for amplifyhosting

> amplify-react-rest@0.1.0 build
> react-scripts build

Creating an optimized production build...
Failed to compile.
@floating-ui/core/dist/floating-ui.core.browser.min.mjs: Cannot read properties of undefined (reading 'constantViolations')
    at transformFile.next (<anonymous>)
    at run.next (<anonymous>)
    at transform.next (<anonymous>)
```
