### ISSUE TITLE
Enable translation of "or" in ``<amplify-sign-in>`` for federated scenarios

### ISSUE THREAD

**Issue by aquachris** [aws-amplify/amplify-ui#584]
### Is this related to a new or existing framework?

Web Components

### Is this related to a new or existing API?

Authentication, Internationalization

### Describe the feature you'd like to request

I noticed that the string "or" is hardcoded in the in-between section of ``<amplify-sign-in>`` in hybrid sign-in scenarios that allow for both a cognito user pool user and a federated login.

![image](https://user-images.githubusercontent.com/6221198/138558205-f0aeaed3-2fc6-42d2-90cb-93970f53f6f8.png)

### Describe the solution you'd like

This would be a tiny change, namely adding a new field into the Translations object and modifying this line accordingly:

https://github.com/aws-amplify/amplify-js/blob/7cfe5817be664bf09a8766d579970e3f7fe8ef6e/packages/amplify-ui-components/src/components/amplify-sign-in/amplify-sign-in.tsx#L297

using something like `{I18n.get(Translations.OR_TEXT)}` instead of just `or` here.

### Describe alternatives you've considered

I've tried working around the issue manually, but there doesn't seem a way to style or configure the `<amplify-strike>` component individually.

As an alternative to the solution outlined above, the `<amplify-strike>` section could be made into a slot to make it even more customizable.

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by eddiekeller** [comment]
Hey @aquachris , thanks for reaching out. I just merged in an update adding translations for "or" to our new version of the authenticator. Check out our docs - https://ui.docs.amplify.aws/ui/getting-started/installation?platform=react - for info on how to get started with the new version!

**Comment by rienafairefr** [comment]
AFAIK the problem is still there (here for french, with "or" added in I18n.putVocabulariesForLanguage), at least in some cases

![image](https://user-images.githubusercontent.com/758517/149630530-1068de46-b578-47c9-a525-3aabffb72030.png)

```
    "@aws-amplify/ui-components": "^1.9.6",
    "@aws-amplify/ui-react": "^2.1.8",
```
The relevant code (I think) for @aws-amplify/ui-react shows the data-or-line is not translatable

https://github.com/aws-amplify/amplify-ui/blob/6a40c1f9c9449a278e7649955be3ea9474b2a592/packages/react/src/components/Authenticator/FederatedSignIn/FederatedSignIn.tsx#L69
