### ISSUE TITLE
Auth UI on iOS is failing with password managers

### ISSUE THREAD

**Issue by sgandon** [aws-amplify/amplify-ui#6648]
### Before creating a new issue, please confirm:

- [x] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [x] I have tried disabling all browser extensions or using a different browser
- [x] I have tried deleting the node_modules folder and reinstalling my dependencies
- [x] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React Native

### Which UI component?

Authenticator

### How is your app built?

using yarn and expo

### What browsers are you seeing the problem on?

iOS (React Native)

### Please describe your bug.

When using the Authenticator UI and using Dashlane for setting the user and password, the email field is considered invalid but it is valid.

<img width="370" height="1832" alt="Image" src="https://github.com/user-attachments/assets/b102ea35-b6d7-4fa2-87fb-7143b977b451" />

The workaround is adding a space manually and removing it to make the field ok but this is really annoying for a first time user. This give an initial bad impression of the app to the user.

### What's the expected behaviour?

it should just accept a valid email.

### Help us reproduce the bug!

just use the Authenticator ui in a react native app on iOS.
If required I can setup a simple app to show the issue but this is pretty boilerplate.

### Code Snippet

```typescript

<Authenticator.Provider>
      <Authenticator
        signUpAttributes={["family_name"]}
        Container={(props) => (
          <Authenticator.Container
            {...props}
            style={{ backgroundColor: colors.background.primary }}
          />
        )}
        Header={MyAppHeader} 
      >
        <UserContextProvider>
....
```

**Comment by ahmedhamouda78** [comment]
Hi @sgandon,
 
Thank you for creating this issue. We will investigate and get back to you once we have more information.

**Comment by ahmedhamouda78** [comment]
Hello @sgandon, this issue has been fixed in PR #6670. It should be available in the next release of the amplify-ui library; we will let you know once that happens. Please feel free to reopen the issue if you have any further questions.

**Comment by ahmedhamouda78** [comment]
Hello @sgandon, the fix has now been released in the latest release of the [Amplify UI React Native](https://github.com/aws-amplify/amplify-ui/releases/tag/%40aws-amplify%2Fui-react-native%402.6.0) library. Please update [@aws-amplify/ui-react-native@2.6.0](https://github.com/aws-amplify/amplify-ui/releases/tag/%40aws-amplify%2Fui-react-native%402.6.0) to get the fix.

**Comment by sgandon** [comment]
Hello
I have tested the fix and it does not work for me :/ 
I have install the 2.6.0 as you can see on this screenshot

<img width="450" height="94" alt="Image" src="https://github.com/user-attachments/assets/9e19ef15-ec6c-46e2-8d89-e58aad96808e" />

And I still have the same issue on my Iphone using dashlane.

<img width="200" height="700" alt="Image" src="https://github.com/user-attachments/assets/7e73ff3c-4860-4d37-80cc-8c84c2210afe" />

Shall I create a new ticket of can someone Reopen this one please ?

**Comment by ahmedhamouda78** [comment]
Hello @sgandon, we will reopen the issue and investigate further. We will let you know when we have any new updates.

**Comment by ahmedhamouda78** [comment]
Hello @sgandon, sorry for the lack of communication! This issue was fixed in the latest release of amplify-ui ([@aws-amplify/ui-react-native@2.6.2](https://github.com/aws-amplify/amplify-ui/releases/tag/%40aws-amplify%2Fui-react-native%402.6.2)). Please update to the latest version to get the fix, and feel free to reopen the issue if you have any further questions.

**Comment by sgandon** [comment]
I am really sorry but this is still failing.
Are you testing the fixes on real device ?
Please reopen.

**Comment by osama-rizk** [comment]
Hi @sgandon, 
> Are you testing the fixes on real device ?

Yes, we verfied the change on actual device (IPhone 11) and we tested it using IPhone password manger

**Comment by sgandon** [comment]
Hello
it was not working on the version you mentioned above `2.6.2` because the fix was not part of this release.
I have just updated to 2.6.3 and it works !
Here is the release note that mentions the fix : https://github.com/aws-amplify/amplify-ui/releases/tag/%40aws-amplify%2Fui-react-native%402.6.3

Thanks a lot for you work ! it is indeed fixed in the 2.6.3
